### ISSUE TITLE
How to use it as api endpoint?

### ISSUE THREAD

**Issue by mboveiri** [hngi/node-url-shortener#182]

**Comment by seyiogunjuyigbe** [comment]
@mboveiri can you be more specific about what you have in mind?

**Comment by mboveiri** [comment]
is able to use Trim as RESTful API.?

for example : 

POST {"longurl":"google.com"} domain.tld/api/short  : Create a new short url

**Comment by seyiogunjuyigbe** [comment]
Apologies for the late response. Yes it is possible @mboveiri. Use [this docs](https://trim.ng/docs) for reference:
